all: hi3520dv200_family

hi3520dv200:
	cat peri_crg.rdl ddrc.rdl mux.rdl sysctl.rdl hi3520dv200.rdl > ../hi3520dv200_chip.rdl

hi3520dv200_family:
	cat peri_crg.rdl ddrc.rdl mux.rdl sysctl.rdl hi3520dv200.rdl > ../hi3520dv200.rdl
